### ISSUE TITLE
rmapy upload fails

### ISSUE THREAD

**Issue by faroit** [opal06/zotero2remarkable_bridge#3]
next issue, some accounts can't upload with rmapy as mentioned here: 

https://github.com/subutux/rmapy/issues/31

**Comment by faroit** [comment]
maybe switch to https://github.com/juruen/rmapi would make it more stable?

**Comment by opal06** [comment]
This is the main issue atm. rmapi could be an alternative, but unfortunately it's written as an interactive application and written in Go, not as a python library. And while it seems that you can run commands non-interactively and one can run cli programs easily  in python by using the subprocess module, this is not a really clean way to implement such a thing and comes with some problems, like no real return values beyond "success" (returns 0) or "fail" (returns 1).

I think the way to go is rather looking at how rmapi handles the new 1.5 reMarkable api and try to implement that for rmapy, either by making a pull request or forking it.

**Comment by opal06** [comment]
I have now experimented some more with python's subprocess module and found it more than capable enough to implement reMarkable cloud API access through rmapi. So I have rewritten the program to use rmapi which should fix issues related to the newer cloud API versions. You can find this version under the rmapi_workaround branch of this repo. I have updated the Readme to show how to change branches.

I have not come around to test this implementation thoroughly though, so please feel free to give it a try and report any bugs found, but be aware that it might not work perfectly yet. If you find any bugs, please open new issues, so it's easier to keep track of them. I will close this issue for now.

**Comment by faroit** [comment]
@opal06 Thats great. I will give it a try asap
