### ISSUE TITLE
python does not create a config file

### ISSUE THREAD

**Issue by scheuerbauer** [opal06/zotero2remarkable_bridge#9]
all parts installed, firing up the python script, it welcomes me and wants me to hit Enter in order to start creating the config-file - but then nothing happens. it idles and I am not asked for my zotero credentials or any info which I can see the script should ask for. Any ideas?

**Comment by opal06** [comment]
This is strange, since that's just a simple input() function waiting for confirmation (that's also why it's important to hit Enter and not just any key). Could you specify the python version and operating system you are using?

**Comment by scheuerbauer** [comment]
sure: I am on a Win10 computer with Git Bash, running rmapi by ddvk https://github.com/ddvk/rmapi and python 3.12. I did clone your repository, pull the requirements, cd'ed to the installation, fired up python and got the "welcome message" (Couldn't find....), hit "Enter"....and nothing

**Comment by opal06** [comment]
I have tried to reproduce the issue on a Windows 10 VM which I configured with Git Bash (both MinTTY terminal and default Windows CMD) and latest Python 3.12 package for Windows (3.12.7), but I wasn't able to. As you can see from the screenshot attached, the config questions come up as expected. Please try to check if there are any updates available for Windows, Git on Windows and Python, maybe it comes down to a bug that has been fixed upstream.

![Screenshot](https://github.com/user-attachments/assets/21ef0ddd-37c4-4c3f-8572-1ab1e70e2bf3)

Anyway, you can just create the config manually. Just copy the following template into a file named "config.yml" in the same directory as the script and add the values yourself:

```yaml
# Folders on Remarkable Tablet
UNREAD_FOLDER: 
READ_FOLDER: 
# Zotero Library info
API_KEY:                                                
LIBRARY_ID:              
LIBRARY_TYPE: user
USE_WEBDAV:                       # 'True' or 'False'; remove following keys if 'False'
WEBDAV_HOSTNAME: 
WEBDAV_PWD: 
WEBDAV_USER: 
```

**Comment by scheuerbauer** [comment]
Thx. Setting it up manually helped - at least for one step...now I don't know how to troubleshoot the following error when trying to push (after all settings set correctly, rmapi working, etc.)
![grafik](https://github.com/user-attachments/assets/07b14360-eaee-4eed-8130-3a0d3d7d1552)
Any help appreciated

**Comment by opal06** [comment]
The error itself was caused by a logic issue, where the variable could not be defined in certain cases. I just pushed a commit that should fix it. But this bug would only appear if the script fails to actually get the file from Zotero, so it probably won't help you get the file on the tablet. Precisely, the step failing is the download from Zotero. Please double check the library ID, API key and whether you are using WebDAV or Zotero's own cloud storage for syncing.

**Comment by scheuerbauer** [comment]
Thx. This now worked after me also correcting my config file (had forgotten to set ' around True...)
